PRINT_ROUND_LOG = False

SIMPLE_GAME = True

MAX_WIDTH = 6
MAX_HEIGHT = 6
# NUM_CHANNELS should match channel-dimension of profit_gym.grid_to_observation()
NUM_CHANNELS = 4

# NUM_SUBBUILDINGS may be reduced to 8 (instead of 16). mine/combiners not crucial (at least for now)

if SIMPLE_GAME:
    NUM_SUBBUILDINGS = 4
else:
    NUM_SUBBUILDINGS = 16
NUM_DIRECTIONS = 4
NUM_ACTIONS = NUM_DIRECTIONS * NUM_SUBBUILDINGS

LEARNING_RATE = 0.0001
GAMMA = 0.7


COMMON_CONV_SIZE = 128
COMMON_CONV_DEPTH = 4
COMMON_DENSE_SIZE = 128
COMMON_DENSE_DEPTH = 1
UNIQUE_DENSE_SIZE = 64

SUCCESS_REWARD = 1
LEGAL_REWARD = 0
ILLEGAL_REWARD = 0
