PRINT_ROUND_LOG = False

MAX_WIDTH = 30
MAX_HEIGHT = 15
NUM_CHANNELS = 4  # should match channel-dimension of profit_gym.grid_to_observation()

NUM_SUBBUILDINGS = 16
NUM_DIRECTIONS = 4
NUM_ACTIONS = NUM_DIRECTIONS * NUM_SUBBUILDINGS

LEARNING_RATE = 0.1

CONV_SIZE = 32
CONV_DEPTH = 2
DENSE_SIZE = 64
DENSE_DEPTH = 1

SUCCESS_REWARD = 1
LEGAL_REWARD = 1
ILLEGAL_REWARD = 0
